# Generated by Django 5.2.13 on 2026-04-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('species', models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('horse', 'Horse'), ('cow', 'Cow'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('exotic', 'Exotic'), ('wildlife', 'Wildlife')], max_length=40)),
                ('system', models.CharField(blank=True, choices=[('respiratory', 'Respiratory'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('reproductive', 'Reproductive'), ('urinary', 'Urinary'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('endocrine', 'Endocrine'), ('infectious_disease', 'Infectious disease'), ('pharmacology', 'Pharmacology'), ('surgery', 'Surgery'), ('anaesthesia', 'Anaesthesia'), ('emergency_critical_care', 'Emergency and critical care'), ('public_health', 'Public health')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('horse', 'Horse'), ('cow', 'Cow'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('exotic', 'Exotic'), ('wildlife', 'Wildlife')], max_length=40)),
                ('system', models.CharField(choices=[('respiratory', 'Respiratory'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('reproductive', 'Reproductive'), ('urinary', 'Urinary'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('endocrine', 'Endocrine'), ('infectious_disease', 'Infectious disease'), ('pharmacology', 'Pharmacology'), ('surgery', 'Surgery'), ('anaesthesia', 'Anaesthesia'), ('emergency_critical_care', 'Emergency and critical care'), ('public_health', 'Public health')], max_length=60)),
                ('explanation', models.TextField()),
                ('exam_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='study_resources/')),
                ('external_url', models.URLField(blank=True)),
                ('species', models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('horse', 'Horse'), ('cow', 'Cow'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('exotic', 'Exotic'), ('wildlife', 'Wildlife')], max_length=40)),
                ('system', models.CharField(blank=True, choices=[('respiratory', 'Respiratory'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('reproductive', 'Reproductive'), ('urinary', 'Urinary'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('endocrine', 'Endocrine'), ('infectious_disease', 'Infectious disease'), ('pharmacology', 'Pharmacology'), ('surgery', 'Surgery'), ('anaesthesia', 'Anaesthesia'), ('emergency_critical_care', 'Emergency and critical care'), ('public_health', 'Public health')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.forumtopic')),
            ],
            options={
                'verbose_name_plural': 'Forum replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('quiz_attempt', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_attempts', through='core.UserAnswer', to='core.question'),
        ),
    ]
