# Generated by Django 5.2.13 on 2026-04-29 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_forest_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('week_label', models.CharField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('species', models.CharField(blank=True, choices=[('general', 'General'), ('dog', 'Dog'), ('cat', 'Cat'), ('horse', 'Horse'), ('cow', 'Cow'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('exotic', 'Exotic'), ('wildlife', 'Wildlife')], max_length=40)),
                ('system', models.CharField(blank=True, choices=[('general', 'General'), ('respiratory', 'Respiratory'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('reproductive', 'Reproductive'), ('urinary', 'Urinary'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('endocrine', 'Endocrine'), ('infectious_disease', 'Infectious disease'), ('pharmacology', 'Pharmacology'), ('surgery', 'Surgery'), ('anaesthesia', 'Anaesthesia'), ('emergency_critical_care', 'Emergency and critical care'), ('public_health', 'Public health')], max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'week_label', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='studyresource',
            options={'ordering': ['resource_type', 'title']},
        ),
        migrations.AddField(
            model_name='studyresource',
            name='resource_type',
            field=models.CharField(choices=[('guideline', 'General guideline'), ('external_link', 'External link')], default='guideline', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_scheme',
            field=models.CharField(choices=[('classic', 'Classic'), ('ocean', 'Ocean'), ('plum', 'Plum'), ('contrast', 'High contrast')], default='classic', max_length=30),
        ),
        migrations.CreateModel(
            name='WeeklyTopicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='weekly_topics/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.weeklystudytopic')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.weeklystudytopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
