# Generated by Django 5.2.13 on 2026-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_weeklystudytopic_alter_studyresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='exam_mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('timed', 'Timed exam')], default='practice', max_length=20),
        ),
    ]
