# Generated by Django 5.2.13 on 2026-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quizattempt_duration_minutes_quizattempt_exam_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='RCVS Prep', max_length=120)),
                ('tagline', models.CharField(default='Clinical exam practice', max_length=180)),
                ('header_brand_text', models.CharField(default='RCVS Prep', max_length=120)),
                ('logo_text', models.CharField(default='RC', max_length=12)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='site_brand/')),
                ('landing_headline', models.CharField(default='Clinical exam prep for modern veterinary teams', max_length=200)),
                ('landing_subheadline', models.TextField(default='Prepare with focused MCQs, flashcards, and study resources designed for RCVS success.')),
                ('support_text', models.CharField(blank=True, default='Support: support@example.com', max_length=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
